# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7bbe9e0da8ef672a315728ff833c3edb41028113c1af77036c3a4942a208a3ff38a80e42c1739237bb121f78dd0b857af7271e15ae2eaf6a7aebce08afad165

test:
  secret_key_base: 9e53e9c2c2225632625badc2ea640f2b223c2300e22aad08eef357601f1ef390526262ad25d83d9abf78e01247676cd405e841b538029486cd8c3e2fcb1c0ae7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
